### ISSUE TITLE
Problema para instalar 

### ISSUE THREAD

**Issue by brunoribas68** [cagartner/bagisto-correios#1]
Using version dev-master for cagartner/bagisto-correios
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
**Your requirements could not be resolved to an installable set of packages.**

  Problem 1
    - Can only install one of: sabberworm/php-css-parser[8.3.0, 8.1.0].
    - Can only install one of: sabberworm/php-css-parser[8.1.0, 8.3.0].
    - Can only install one of: sabberworm/php-css-parser[8.1.0, 8.3.0].
    - cagartner/phpquery 0.9.10 requires sabberworm/php-css-parser 8.1.* -> satisfiable by sabberworm/php-css-parser[8.1.0].
    - cagartner/bagisto-correios dev-master requires cagartner/phpquery 0.9.10 -> satisfiable by cagartner/phpquery[0.9.10].
    - Installation request for cagartner/bagisto-correios dev-master -> satisfiable by cagartner/bagisto-correios[dev-master].
    - Installation request for sabberworm/php-css-parser (locked at 8.3.0) -> satisfiable by sabberworm/php-css-parser[8.3.0].

### Installation failed, reverting ./composer.json to its original content.

**Comment by cagartner** [comment]
Olá @brunoribas68 

Atualizei a versão do php-css-parser, agora não deve dar mais erro.

Por favor antes de testar novamente limpe o cache do composer

`composer clearcache`

Abraços!

**Comment by cagartner** [comment]
Fechando por falta de retorno

**Comment by brunoribas68** [comment]
Bom dia,

Peço desculpas pela demora no retorno, muito obrigado.

Sua extensão é fenomenal parabéns pelo trabalho.



Em sex, 1 de nov de 2019 10:01, Carlos Augusto Gartner <
notifications@github.com> escreveu:

**Comment by devpelegrine** [comment]
Olá fui instalar o modulo do correios e retornou este erro: 

composer require cagartner/bagisto-correios
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^0.2.1 for cagartner/bagisto-correios
./composer.json has been updated
Running composer update cagartner/bagisto-correios
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cagartner/phpquery 0.9.11 requires sabberworm/php-css-parser 8.3.* -> found sabberworm/php-css-parser[8.3.0, 8.3.1] but the package is fixed to 8.4.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - cagartner/bagisto-correios 0.2.1 requires cagartner/phpquery 0.9.11 -> satisfiable by cagartner/phpquery[0.9.11].
    - Root composer.json requires cagartner/bagisto-correios ^0.2.1 -> satisfiable by cagartner/bagisto-correios[0.2.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require cagartner/bagisto-correios:*" to figure out if any version is installable, or "composer require cagartner/bagisto-correios:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
