### ISSUE TITLE
correios internacional

### ISSUE THREAD

**Issue by marcelowu** [cagartner/bagisto-correios#2]
ola, pretende colocar correios internacional? tipo ems ou leve internacional. preciso vender para outros paises.. e a versao PWA vai ter tbm?

**Comment by cagartner** [comment]
Opa e ai.

No momento não tenho tempo livre para implementar isso, na verdade até acredito que seria melhor criar um novo módulo para Correios Internacional.

Você pode se basear nesse módulo para fazer, é bem simples na verdade.

Qualquer dúvida pode entrar em contato comigo: contato@carlosgartner.com.br

Abraços!
