### ISSUE TITLE
calcular automatica depois preenchimento do cep

### ISSUE THREAD

**Issue by marcelowu** [cagartner/bagisto-correios#7]
Finalizar Compra endereço de Cobrança  depois de preencher tudo ate o telefone o modulo nao calcula o valor, tem q clicar qualquer lugar da pagina para poder calcular..
possivel assim q o cep eh preenchido ja calcula automatica

**Comment by cagartner** [comment]
Isso na verdade é uma issue do tema e não do módulo de método de entrega, você tem que abrir uma issue no Bagisto sobre isso ou forçar a execusão do trigger de shipping methods no seu tema.

**Comment by marcelowu** [comment]
como explico la em ingles, nem brasileiro falo direito, pode me ajuda a explica la
